language: python
python:
  - 2.7


before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  - "pip install -r req.txt"
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  - ansible-playbook -i tests/hosts tests/main.yml --syntax-check
  - ansible-playbook -i tests/hosts tests/main.yml --connection=local --sudo
  - >
    ansible-playbook -i tests/hosts tests/main.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - pyenv versions
  - pyenv global
