---
- name: download pyenv-install.sh
  get_url:
    url=https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer
    dest=/home/test/pyenv.sh
    mode=0744

- name: run the installer
  script: /home/test/pyenv.sh

- name: debug
  shell: cat ~/.bash_profile
  args:
    executable: /bin/bash

- name: debug
  shell: echo `pwd` `whoami`
  args:
    executable: /bin/bash

- name: pyenv update
  shell: pyenv update
  args:
    executable: /bin/bash

- name: install python versions
  shell: pyenv install {{ item }}
  args:
    executable: /bin/bash
  with_items: "{{ python.versions }}"

- name: set global python
  command: pyenv global {{ python.default }}
