---
- name: create a local temp directory
  command: mktemp -d "{{ lookup('env', 'TMPDIR') | default('/tmp', true) }}/ansible.XXX"
  register: mktemp

- name: download pyenv-install.sh
  get_url:
    url=https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer
    dest="{{ mktemp.stdout }}/pyenv.sh"
    mode=0744

- name: run the installer
  script: "{{ mktemp.stdout }}/pyenv.sh"

- name: update pyenv
  command: pyenv update

- name: install python versions
  command: pyenv install {{ item }}
  with_items: "{{ python.versions }}"

- name: set global python
  command: pyenv global {{ python.default }}
