---
- name: download pyenv-install.sh
  get_url:
    url=https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer
    dest=/home/test/pyenv.sh
    mode=0744

- name: run the installer
  script: /home/test/pyenv.sh

- name: ensure bash_profile
  shell: touch ~/.bash_profile

- name: update PATH
  lineinfile:
    dest=~/.bash_profile
    line='export PATH="$HOME/.pyenv/bin:$PATH"'

- name: init pyenv with bash
  lineinfile:
    dest=~/.bash_profile
    line='eval "$(pyenv init -)"'

- name: pyenv update
  shell: . ~/.bash_profile && pyenv update
  args:
    executable: /bin/bash

- name: install python versions
  shell: . ~/.bash_profile && pyenv install {{ item }}
  args:
    executable: /bin/bash
  with_items: "{{ python.versions }}"

- name: set global python
  shell: . ~/.bash_profile && pyenv global {{ python.default }}
